### ISSUE TITLE
Missing columns

### ISSUE THREAD

**Issue by linusblom** [chas-academy/07-trello-clone-jonastore#2]
Dragging and dropping cards in columns TODO, DOING and DONE is a part of the assignment. I can se columns but I can not drop cards in them.

It is possible to use only sortable (not draggable and droppable) and jQuery UI will take care of almost everything. It is of course ok to use draggable and droppable, but then you may need to uncomment the commented out code in index.html.

Also as part of the requirements for this assignment you need to supply a basic implementation of either a) a plugin/widget using the jQuery UI Widget factory or b) the jQuery plugin factory.

Please refer to one of the patterns that are defined and available in this repository:

https://github.com/jquery-boilerplate/jquery-patterns
Extra note: The plugin doesn't have to be that complex, just toggle some CSS property or manipulate the selector in the DOM somehow, text or similar.

**Comment by jonastore** [comment]
The design was sort of changed last minute, so things are a bit unclear. Inside the settings tab of the card is a form used to create cards that can in fact be sorted between in columns. The widget is also there, although it's very basic. Right beneath the "Welcome to Jonas Kanban" headline there's this input field that shows the current year. It's also located in the root folder under the name yearclock.js if you want to take a closer look.

**Comment by linusblom** [comment]
Thanks for the explanation, now see the widget and got drag-and-drop it to work :)
